### ISSUE TITLE
新版本好卡

### ISSUE THREAD

**Issue by ILO170** [I-hope1/mod-tools#15]
之前用的1.43版本还能在游戏中正常运行 现在更新到1.5运行游戏就只剩下1或者2帧了

**Comment by I-hope1** [comment]
az，能发截图吗？

**Comment by ILO170** [comment]
az 我把游戏数据导出后清除游戏数据再导入就不卡了

之前卡的时候
只加载这一个模组并且游戏暂停还是会卡 只要进入游戏地图就会卡

**Comment by I-hope1** [comment]
Hash导致的内存问题吧，1.5.1应该修了
