### ISSUE TITLE
新版本有些功能无法使用

### ISSUE THREAD

**Issue by ILO170** [I-hope1/mod-tools#16]
![001.jpg](https://github.com/user-attachments/assets/e2375a82-4dde-4f7f-9faa-42d0ec05849d)
![002.jpg](https://github.com/user-attachments/assets/9b42d9cd-6f52-473d-88d4-22a93da4aa06)

001图片是1.5.1版本的 打开后无法选中建筑 
staticselect选中什么也没发生 dynamicselect选中只有一个蓝色的框
 
002图片是1.4.3版本的 可以选中并且能修改

**Comment by I-hope1** [comment]
这不算bug吧，设置里可以开启对应的选择
