### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by dmgnr** [I-hope1/mod-tools#3]
Only capture scroll wheel if hover on one of the mod element please

**Comment by dmgnr** [comment]
When

**Comment by I-hope1** [comment]
I don't quite understand what you say.
Maybe the mod elements capture scroll focus making game scaling unusable?
See [修复Window阻塞输入的bug，一些代码调整](https://github.com/I-hope1/mod-tools/commit/8d87d0d9dbc4c532ff1a984e4750b48873ad4e77)

**Comment by dmgnr** [comment]
That looks like the right commit for this issue 👍
